### ISSUE TITLE
Can't inject dependencies with generics to Jersey resources

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey#33]
This was first reported on the [Bootique forum](https://groups.google.com/forum/#!topic/bootique-user/TfnLLLTYo9Q). Bootique Jersey injection bridge doesn't work for resources that inject services with generics parameters. I can reproduce in a unit test. From ignored `ResourceInjection_GenericsIT.testFieldInjected` :

```java
@Path("/f")
public static class FieldInjectedResource {

    @Inject
    private S1<Integer> intService;
    @Inject
    private S1<String> stringService;

    @GET
    public String get() {
        return "f_" + intService.asString() + "_" + stringService.asString();
    }
}
```

This results in the following exception on startup:

```
[pool-1-thread-1] WARN / - unavailable
java.lang.IllegalStateException: Can't process injection point: io.bootique.jersey.ResourceInjection_GenericsIT.io.bootique.jersey.ResourceInjection_GenericsIT$S1<java.lang.Integer>
	at io.bootique.jersey.GuiceInjectInjector.resolve(GuiceInjectInjector.java:60)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:946)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:981)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:971)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:602)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:182)
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:348)
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:345)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:345)
```

At the same time injection of `S1<Integer>` and `S1<String>` elsewhere in Guice works, so there's an easy workaround - a provider method.

**Don't forget to un-@Ignore the test in question once this is fixed**

**Comment by andrus** [comment]
Solved by #39 and #42
