### ISSUE TITLE
StackOverflowError in Jersey 2.21

### ISSUE THREAD

**Issue by IRus** [bootique/bootique-jersey#34]
When I use `trace` log level, I got `StakOverflowError` when application starting.

Problem can be solved by upgrading `jersey-container-servlet` to `2.21.1`. Btw latest vesrion `2.26` doen't work with this module.

```
DEBUG [2017-12-20 12:07:59,647] main org.jvnet.hk2.logger: ServiceLocator ServiceLocatorImpl(jersey-server-rd-locator,1,831993944) has been shutdown
INFO  [2017-12-20 12:07:59,673] main o.e.j.s.ServerConnector: Started ServerConnector@68ef01a5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Error running command '--server --config=run.yml': Command exception.
java.lang.StackOverflowError
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:91)
	at java.base/java.lang.Object.toString(Object.java:246)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.glassfish.jersey.server.model.Resource$Builder.toString(Resource.java:676)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.glassfish.jersey.server.model.Resource$Builder.toString(Resource.java:676)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
```

https://github.com/jersey/jersey/issues/3225

**Comment by andrus** [comment]
Presumably fixed per #38
