### ISSUE TITLE
Java 17 compatibility - Jersey 2.35 upgrade

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey#62]
While our tests work on java 17, there were user reports that Bootique with Jersey 2.30.1 breaks on Java 17 with a stack like the one below. According to [this](https://stackoverflow.com/questions/68603262/how-to-fix-unsupported-class-file-major-version-60-in-tomcat9), Jersey >= 2.34 is required for Java 17 compatibility, so we need to upgrade Jersey to 2.35. 

* This DOES NOT affect Bootique 3.x that is already on the latest versions of Jersey
* We can't catch it in our tests because the default compiler settings are Java 1.8 compatible, even when we compile on 17.

```
java.lang.IllegalArgumentException: Unsupported class file major version 61
at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:201)
at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:179)
at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:165)
at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:289)
at org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener.process(AnnotationAcceptingListener.java:148)
at org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:919)
...
at org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1182)
at org.glassfish.jersey.server.ApplicationHandler$RuntimeConfigConfigurator.init(ApplicationHandler.java:182)
at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$0(ApplicationHandler.java:290)
at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:290)
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
at javax.servlet.GenericServlet.init(GenericServlet.java:244)
...
at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
...
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at io.bootique.jetty.command.ServerCommand.run(ServerCommand.java:52)
```

## Upgrade Notes

The upgrade to Jersey 2.35 also causes an upgrade of the underlying JAX-RS spec from 2.1.1 to 2.1.6. At the code level the tow are identical (there are only Javadoc changes), but the latter is now in `jakarta.ws.rs:jakarta.ws.rs-api` modules (the former was in `javax.ws.rs:javax.ws.rs-api`)

**Comment by andrus** [comment]
The fix requires an upgrade to `bootique-modules-parent` v 2.0.8 (see https://github.com/bootique/bootique-modules-parent/issues/50)
